add_rules("mode.debug", "mode.release")

target("sysifus")
  set_kind("shared")
  set_languages("c99")
  set_warnings("all", "error")
  add_files("src/*.c")
  add_headerfiles("include/*.h")
  add_includedirs("include", { public = true })
  set_pcheader("include/luts.h")

target("test")
  set_kind("binary")
  set_languages("c99")
  set_warnings("all", "error")
  add_files("test/main.c")
  add_deps("sysifus")
  add_includedirs("include")
  add_links("check")
